name: CI


on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:

  wsserver:

    runs-on: ubuntu-latest
   
    steps:
      
      

  mobile:

    runs-on: ubuntu-latest



    steps:

  windows-client:

  